/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockCheck4bb144df5336RouteImport } from './routes/stock-check-4bb144df5336'
import { Route as ServiceQueueRouteImport } from './routes/service-queue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTrainingRouteImport } from './routes/_app.training'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppStockTransfersRouteImport } from './routes/_app.stock-transfers'
import { Route as AppShiftsRouteImport } from './routes/_app.shifts'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRefundsRouteImport } from './routes/_app.refunds'
import { Route as AppRecruitmentRouteImport } from './routes/_app.recruitment'
import { Route as AppQuotationsRouteImport } from './routes/_app.quotations'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app.purchase-orders'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppOvertimeRouteImport } from './routes/_app.overtime'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMarketingRouteImport } from './routes/_app.marketing'
import { Route as AppLoyaltyRouteImport } from './routes/_app.loyalty'
import { Route as AppLeavesRouteImport } from './routes/_app.leaves'
import { Route as AppJobOrdersRouteImport } from './routes/_app.job-orders'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppGarageRouteImport } from './routes/_app.garage'
import { Route as AppFitmentRouteImport } from './routes/_app.fitment'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppEcommerceRouteImport } from './routes/_app.ecommerce'
import { Route as AppDiscountsRouteImport } from './routes/_app.discounts'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppCashFlowRouteImport } from './routes/_app.cash-flow'
import { Route as AppCashDrawerRouteImport } from './routes/_app.cash-drawer'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppAuditLogRouteImport } from './routes/_app.audit-log'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppMyIndexRouteImport } from './routes/_app.my.index'
import { Route as AppMyQueueRouteImport } from './routes/_app.my.queue'
import { Route as AppMyPerformanceRouteImport } from './routes/_app.my.performance'
import { Route as AppMyPayslipsRouteImport } from './routes/_app.my.payslips'
import { Route as AppMyLeavesRouteImport } from './routes/_app.my.leaves'
import { Route as AppMyAttendanceRouteImport } from './routes/_app.my.attendance'

const StockCheck4bb144df5336Route = StockCheck4bb144df5336RouteImport.update({
  id: '/stock-check-4bb144df5336',
  path: '/stock-check-4bb144df5336',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceQueueRoute = ServiceQueueRouteImport.update({
  id: '/service-queue',
  path: '/service-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockTransfersRoute = AppStockTransfersRouteImport.update({
  id: '/stock-transfers',
  path: '/stock-transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRefundsRoute = AppRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentRoute = AppRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppOvertimeRoute = AppOvertimeRouteImport.update({
  id: '/overtime',
  path: '/overtime',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppLeavesRoute = AppLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppJobOrdersRoute = AppJobOrdersRouteImport.update({
  id: '/job-orders',
  path: '/job-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGarageRoute = AppGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AppRoute,
} as any)
const AppFitmentRoute = AppFitmentRouteImport.update({
  id: '/fitment',
  path: '/fitment',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppEcommerceRoute = AppEcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscountsRoute = AppDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppCashDrawerRoute = AppCashDrawerRouteImport.update({
  id: '/cash-drawer',
  path: '/cash-drawer',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppMyIndexRoute = AppMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => AppRoute,
} as any)
const AppMyQueueRoute = AppMyQueueRouteImport.update({
  id: '/my/queue',
  path: '/my/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppMyPerformanceRoute = AppMyPerformanceRouteImport.update({
  id: '/my/performance',
  path: '/my/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppMyPayslipsRoute = AppMyPayslipsRouteImport.update({
  id: '/my/payslips',
  path: '/my/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLeavesRoute = AppMyLeavesRouteImport.update({
  id: '/my/leaves',
  path: '/my/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAttendanceRoute = AppMyAttendanceRouteImport.update({
  id: '/my/attendance',
  path: '/my/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/service-queue': typeof ServiceQueueRoute
  '/stock-check-4bb144df5336': typeof StockCheck4bb144df5336Route
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-log': typeof AppAuditLogRoute
  '/bookings': typeof AppBookingsRoute
  '/cash-drawer': typeof AppCashDrawerRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/crm': typeof AppCrmRoute
  '/customers': typeof AppCustomersRoute
  '/departments': typeof AppDepartmentsRoute
  '/discounts': typeof AppDiscountsRoute
  '/ecommerce': typeof AppEcommerceRoute
  '/employees': typeof AppEmployeesRoute
  '/feedback': typeof AppFeedbackRoute
  '/finance': typeof AppFinanceRoute
  '/fitment': typeof AppFitmentRoute
  '/garage': typeof AppGarageRoute
  '/inventory': typeof AppInventoryRoute
  '/job-orders': typeof AppJobOrdersRoute
  '/leaves': typeof AppLeavesRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/marketing': typeof AppMarketingRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/overtime': typeof AppOvertimeRoute
  '/payments': typeof AppPaymentsRoute
  '/payroll': typeof AppPayrollRoute
  '/performance': typeof AppPerformanceRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/quotations': typeof AppQuotationsRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/refunds': typeof AppRefundsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/stock-transfers': typeof AppStockTransfersRoute
  '/suppliers': typeof AppSuppliersRoute
  '/training': typeof AppTrainingRoute
  '/users': typeof AppUsersRoute
  '/my/attendance': typeof AppMyAttendanceRoute
  '/my/leaves': typeof AppMyLeavesRoute
  '/my/payslips': typeof AppMyPayslipsRoute
  '/my/performance': typeof AppMyPerformanceRoute
  '/my/queue': typeof AppMyQueueRoute
  '/my/': typeof AppMyIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/service-queue': typeof ServiceQueueRoute
  '/stock-check-4bb144df5336': typeof StockCheck4bb144df5336Route
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-log': typeof AppAuditLogRoute
  '/bookings': typeof AppBookingsRoute
  '/cash-drawer': typeof AppCashDrawerRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/crm': typeof AppCrmRoute
  '/customers': typeof AppCustomersRoute
  '/departments': typeof AppDepartmentsRoute
  '/discounts': typeof AppDiscountsRoute
  '/ecommerce': typeof AppEcommerceRoute
  '/employees': typeof AppEmployeesRoute
  '/feedback': typeof AppFeedbackRoute
  '/finance': typeof AppFinanceRoute
  '/fitment': typeof AppFitmentRoute
  '/garage': typeof AppGarageRoute
  '/inventory': typeof AppInventoryRoute
  '/job-orders': typeof AppJobOrdersRoute
  '/leaves': typeof AppLeavesRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/marketing': typeof AppMarketingRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/overtime': typeof AppOvertimeRoute
  '/payments': typeof AppPaymentsRoute
  '/payroll': typeof AppPayrollRoute
  '/performance': typeof AppPerformanceRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/quotations': typeof AppQuotationsRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/refunds': typeof AppRefundsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/stock-transfers': typeof AppStockTransfersRoute
  '/suppliers': typeof AppSuppliersRoute
  '/training': typeof AppTrainingRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/my/attendance': typeof AppMyAttendanceRoute
  '/my/leaves': typeof AppMyLeavesRoute
  '/my/payslips': typeof AppMyPayslipsRoute
  '/my/performance': typeof AppMyPerformanceRoute
  '/my/queue': typeof AppMyQueueRoute
  '/my': typeof AppMyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/service-queue': typeof ServiceQueueRoute
  '/stock-check-4bb144df5336': typeof StockCheck4bb144df5336Route
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/cash-drawer': typeof AppCashDrawerRoute
  '/_app/cash-flow': typeof AppCashFlowRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/discounts': typeof AppDiscountsRoute
  '/_app/ecommerce': typeof AppEcommerceRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/fitment': typeof AppFitmentRoute
  '/_app/garage': typeof AppGarageRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/job-orders': typeof AppJobOrdersRoute
  '/_app/leaves': typeof AppLeavesRoute
  '/_app/loyalty': typeof AppLoyaltyRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/overtime': typeof AppOvertimeRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/recruitment': typeof AppRecruitmentRoute
  '/_app/refunds': typeof AppRefundsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/stock-transfers': typeof AppStockTransfersRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/training': typeof AppTrainingRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/my/attendance': typeof AppMyAttendanceRoute
  '/_app/my/leaves': typeof AppMyLeavesRoute
  '/_app/my/payslips': typeof AppMyPayslipsRoute
  '/_app/my/performance': typeof AppMyPerformanceRoute
  '/_app/my/queue': typeof AppMyQueueRoute
  '/_app/my/': typeof AppMyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/service-queue'
    | '/stock-check-4bb144df5336'
    | '/analytics'
    | '/attendance'
    | '/audit-log'
    | '/bookings'
    | '/cash-drawer'
    | '/cash-flow'
    | '/crm'
    | '/customers'
    | '/departments'
    | '/discounts'
    | '/ecommerce'
    | '/employees'
    | '/feedback'
    | '/finance'
    | '/fitment'
    | '/garage'
    | '/inventory'
    | '/job-orders'
    | '/leaves'
    | '/loyalty'
    | '/marketing'
    | '/notifications'
    | '/orders'
    | '/overtime'
    | '/payments'
    | '/payroll'
    | '/performance'
    | '/pos'
    | '/products'
    | '/purchase-orders'
    | '/quotations'
    | '/recruitment'
    | '/refunds'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/shifts'
    | '/stock-transfers'
    | '/suppliers'
    | '/training'
    | '/users'
    | '/my/attendance'
    | '/my/leaves'
    | '/my/payslips'
    | '/my/performance'
    | '/my/queue'
    | '/my/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/service-queue'
    | '/stock-check-4bb144df5336'
    | '/analytics'
    | '/attendance'
    | '/audit-log'
    | '/bookings'
    | '/cash-drawer'
    | '/cash-flow'
    | '/crm'
    | '/customers'
    | '/departments'
    | '/discounts'
    | '/ecommerce'
    | '/employees'
    | '/feedback'
    | '/finance'
    | '/fitment'
    | '/garage'
    | '/inventory'
    | '/job-orders'
    | '/leaves'
    | '/loyalty'
    | '/marketing'
    | '/notifications'
    | '/orders'
    | '/overtime'
    | '/payments'
    | '/payroll'
    | '/performance'
    | '/pos'
    | '/products'
    | '/purchase-orders'
    | '/quotations'
    | '/recruitment'
    | '/refunds'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/shifts'
    | '/stock-transfers'
    | '/suppliers'
    | '/training'
    | '/users'
    | '/'
    | '/my/attendance'
    | '/my/leaves'
    | '/my/payslips'
    | '/my/performance'
    | '/my/queue'
    | '/my'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/service-queue'
    | '/stock-check-4bb144df5336'
    | '/_app/analytics'
    | '/_app/attendance'
    | '/_app/audit-log'
    | '/_app/bookings'
    | '/_app/cash-drawer'
    | '/_app/cash-flow'
    | '/_app/crm'
    | '/_app/customers'
    | '/_app/departments'
    | '/_app/discounts'
    | '/_app/ecommerce'
    | '/_app/employees'
    | '/_app/feedback'
    | '/_app/finance'
    | '/_app/fitment'
    | '/_app/garage'
    | '/_app/inventory'
    | '/_app/job-orders'
    | '/_app/leaves'
    | '/_app/loyalty'
    | '/_app/marketing'
    | '/_app/notifications'
    | '/_app/orders'
    | '/_app/overtime'
    | '/_app/payments'
    | '/_app/payroll'
    | '/_app/performance'
    | '/_app/pos'
    | '/_app/products'
    | '/_app/purchase-orders'
    | '/_app/quotations'
    | '/_app/recruitment'
    | '/_app/refunds'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/shifts'
    | '/_app/stock-transfers'
    | '/_app/suppliers'
    | '/_app/training'
    | '/_app/users'
    | '/_app/'
    | '/_app/my/attendance'
    | '/_app/my/leaves'
    | '/_app/my/payslips'
    | '/_app/my/performance'
    | '/_app/my/queue'
    | '/_app/my/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ServiceQueueRoute: typeof ServiceQueueRoute
  StockCheck4bb144df5336Route: typeof StockCheck4bb144df5336Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-check-4bb144df5336': {
      id: '/stock-check-4bb144df5336'
      path: '/stock-check-4bb144df5336'
      fullPath: '/stock-check-4bb144df5336'
      preLoaderRoute: typeof StockCheck4bb144df5336RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-queue': {
      id: '/service-queue'
      path: '/service-queue'
      fullPath: '/service-queue'
      preLoaderRoute: typeof ServiceQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-transfers': {
      id: '/_app/stock-transfers'
      path: '/stock-transfers'
      fullPath: '/stock-transfers'
      preLoaderRoute: typeof AppStockTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/refunds': {
      id: '/_app/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof AppRefundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment': {
      id: '/_app/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AppRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overtime': {
      id: '/_app/overtime'
      path: '/overtime'
      fullPath: '/overtime'
      preLoaderRoute: typeof AppOvertimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loyalty': {
      id: '/_app/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaves': {
      id: '/_app/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AppLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-orders': {
      id: '/_app/job-orders'
      path: '/job-orders'
      fullPath: '/job-orders'
      preLoaderRoute: typeof AppJobOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garage': {
      id: '/_app/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof AppGarageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fitment': {
      id: '/_app/fitment'
      path: '/fitment'
      fullPath: '/fitment'
      preLoaderRoute: typeof AppFitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecommerce': {
      id: '/_app/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof AppEcommerceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discounts': {
      id: '/_app/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AppDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-flow': {
      id: '/_app/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-drawer': {
      id: '/_app/cash-drawer'
      path: '/cash-drawer'
      fullPath: '/cash-drawer'
      preLoaderRoute: typeof AppCashDrawerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/': {
      id: '/_app/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof AppMyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/queue': {
      id: '/_app/my/queue'
      path: '/my/queue'
      fullPath: '/my/queue'
      preLoaderRoute: typeof AppMyQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/performance': {
      id: '/_app/my/performance'
      path: '/my/performance'
      fullPath: '/my/performance'
      preLoaderRoute: typeof AppMyPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/payslips': {
      id: '/_app/my/payslips'
      path: '/my/payslips'
      fullPath: '/my/payslips'
      preLoaderRoute: typeof AppMyPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/leaves': {
      id: '/_app/my/leaves'
      path: '/my/leaves'
      fullPath: '/my/leaves'
      preLoaderRoute: typeof AppMyLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/attendance': {
      id: '/_app/my/attendance'
      path: '/my/attendance'
      fullPath: '/my/attendance'
      preLoaderRoute: typeof AppMyAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppCashDrawerRoute: typeof AppCashDrawerRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppCrmRoute: typeof AppCrmRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDiscountsRoute: typeof AppDiscountsRoute
  AppEcommerceRoute: typeof AppEcommerceRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFitmentRoute: typeof AppFitmentRoute
  AppGarageRoute: typeof AppGarageRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppJobOrdersRoute: typeof AppJobOrdersRoute
  AppLeavesRoute: typeof AppLeavesRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOvertimeRoute: typeof AppOvertimeRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppRecruitmentRoute: typeof AppRecruitmentRoute
  AppRefundsRoute: typeof AppRefundsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppStockTransfersRoute: typeof AppStockTransfersRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMyAttendanceRoute: typeof AppMyAttendanceRoute
  AppMyLeavesRoute: typeof AppMyLeavesRoute
  AppMyPayslipsRoute: typeof AppMyPayslipsRoute
  AppMyPerformanceRoute: typeof AppMyPerformanceRoute
  AppMyQueueRoute: typeof AppMyQueueRoute
  AppMyIndexRoute: typeof AppMyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppCashDrawerRoute: AppCashDrawerRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppCrmRoute: AppCrmRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDiscountsRoute: AppDiscountsRoute,
  AppEcommerceRoute: AppEcommerceRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFitmentRoute: AppFitmentRoute,
  AppGarageRoute: AppGarageRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppJobOrdersRoute: AppJobOrdersRoute,
  AppLeavesRoute: AppLeavesRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOvertimeRoute: AppOvertimeRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppRecruitmentRoute: AppRecruitmentRoute,
  AppRefundsRoute: AppRefundsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppStockTransfersRoute: AppStockTransfersRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppMyAttendanceRoute: AppMyAttendanceRoute,
  AppMyLeavesRoute: AppMyLeavesRoute,
  AppMyPayslipsRoute: AppMyPayslipsRoute,
  AppMyPerformanceRoute: AppMyPerformanceRoute,
  AppMyQueueRoute: AppMyQueueRoute,
  AppMyIndexRoute: AppMyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ServiceQueueRoute: ServiceQueueRoute,
  StockCheck4bb144df5336Route: StockCheck4bb144df5336Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
